/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CaseContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Studio = {
  _id: string;
  _type: "studio";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  about?: BlockContent;
  selectedProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  clientsCollaborators?: Array<string>;
  consultants?: Array<string>;
  contactBlurb?: BlockContent;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  title?: string;
  slug?: Slug;
  introduction?: string;
  year?: number;
  information?: Array<{
    label?: string;
    value?: string;
    _type: "informationItem";
    _key: string;
  }>;
  caseContent?: CaseContent;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | CaseContent
  | BlockContent
  | ProjectReference
  | Studio
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/projects.ts
// Variable: SELECTED_PROJECTS_QUERY
// Query: *[_id == "studio"][0].selectedProjects[]->{    _id,    title,    "slug": slug.current,    year,    mainImage {   alt,  hotspot,  crop,  asset->{ _id } }  }
export type SELECTED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  year: number | null;
  mainImage: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
    } | null;
  } | null;
}> | null;

// Source: sanity/queries/projects.ts
// Variable: PROJECT_INDEX_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(year desc, title asc) {    _id,    title,    "slug": slug.current  }
export type PROJECT_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
}>;

// Source: sanity/queries/projects.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)].slug.current
export type PROJECT_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: sanity/queries/projects.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && defined(slug.current) && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    year,    introduction,    information[]{ _key, label, value },    mainImage {   alt,  hotspot,  crop,  asset->{ _id } },    caseContent[]{      ...,      markDefs[]{ ..., _type == "link" => { href } },      _type == "image" => {   alt,  hotspot,  crop,  asset->{ _id } }    }  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  year: number | null;
  introduction: string | null;
  information: Array<{
    _key: string;
    label: string | null;
    value: string | null;
  }> | null;
  mainImage: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
    } | null;
  } | null;
  caseContent: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs: Array<{
          href: string | null;
          _type: "link";
          _key: string;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: {
          _id: string;
        } | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
} | null;

// Source: sanity/queries/studio.ts
// Variable: STUDIO_QUERY
// Query: *[_id == "studio"][0]{    about[]{      ...,      markDefs[]{ ..., _type == "link" => { href } }    },    clientsCollaborators,    consultants,    contactBlurb[]{      ...,      markDefs[]{ ..., _type == "link" => { href } }    }  }
export type STUDIO_QUERY_RESULT =
  | {
      about: null;
      clientsCollaborators: null;
      consultants: null;
      contactBlurb: null;
    }
  | {
      about: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs: Array<{
          href: string | null;
          _type: "link";
          _key: string;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      clientsCollaborators: Array<string> | null;
      consultants: Array<string> | null;
      contactBlurb: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs: Array<{
          href: string | null;
          _type: "link";
          _key: string;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "studio"][0].selectedProjects[]->{\n    _id,\n    title,\n    "slug": slug.current,\n    year,\n    mainImage { \n  alt,\n  hotspot,\n  crop,\n  asset->{ _id }\n }\n  }\n': SELECTED_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)] | order(year desc, title asc) {\n    _id,\n    title,\n    "slug": slug.current\n  }\n': PROJECT_INDEX_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)].slug.current\n': PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current) && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    year,\n    introduction,\n    information[]{ _key, label, value },\n    mainImage { \n  alt,\n  hotspot,\n  crop,\n  asset->{ _id }\n },\n    caseContent[]{\n      ...,\n      markDefs[]{ ..., _type == "link" => { href } },\n      _type == "image" => { \n  alt,\n  hotspot,\n  crop,\n  asset->{ _id }\n }\n    }\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_id == "studio"][0]{\n    about[]{\n      ...,\n      markDefs[]{ ..., _type == "link" => { href } }\n    },\n    clientsCollaborators,\n    consultants,\n    contactBlurb[]{\n      ...,\n      markDefs[]{ ..., _type == "link" => { href } }\n    }\n  }\n': STUDIO_QUERY_RESULT;
  }
}
